quarkus.http.cors.origins=${CORS_ORIGINS:https://admin.votersentiment.in}
quarkus.hibernate-orm.database.generation=validate
quarkus.hibernate-orm.log.sql=false
quarkus.log.level=INFO
quarkus.log.console.json=true
